spring:
  application:
    name: fintrace-core
  security:
    oauth2:
          resourceserver:
            jwt:
              audiences: fintrace-core
              
springdoc:
  swagger-ui:
    oauth:
      client-id: fintrace-swagger
      use-pkce-with-authorization-code-grant: true

management:
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: false

jobs:
  cleanWorkspacesBackgroundJob:
    cron: "0 0 3 * * SUN"
    params:
      persistPeriod: 30d

logging:
  pattern:
    correlation: "%X{traceId:-} [user=%X{userId:-}|workspace=%X{workspaceId:-}] "
